name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma Client
        run: bun run prisma:generate

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run build:ci
        env:
          DATABASE_URL: postgresql://user:pass@localhost:5432/ci?schema=public
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: testsecret
          AUTH_TRUST_HOST: true
          GOOGLE_CLIENT_ID: dummy
          GOOGLE_CLIENT_SECRET: dummy
          EMAIL_ENCRYPT_SECRET: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
          EMAIL_ENCRYPT_SALT: 0123456789abcdef0123456789abcdef
